/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * The schema for setting up a new database for the project with sql
 * 
 * @author adath325
 * @version 3.0
 */
CREATE TABLE products (
    productID INTEGER NOT NULL,
    name VARCHAR NOT NULL,
    description VARCHAR NOT NULL,
    category VARCHAR NOT NULL,
    price DECIMAL (4, 2) NOT NULL,
    quantity INTEGER NOT NULL,
    CONSTRAINT pk_products PRIMARY KEY (productID)
);

CREATE TABLE customers (
    userName VARCHAR NOT NULL,
    name VARCHAR NOT NULL,
    email VARCHAR NOT NULL,
    address VARCHAR NOT NULL,
    creditCardDetails VARCHAR NOT NULL,
    password VARCHAR NOT NULL,
    CONSTRAINT pk_customers PRIMARY KEY (userName)
);

CREATE TABLE orders (
    orderID INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 100) NOT NULL,
    date TIMESTAMP NOT NULL,
    customer VARCHAR NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (orderID),
    CONSTRAINT fk_orders_customer FOREIGN KEY (customer) REFERENCES customers(userName)
);

CREATE TABLE items (
    quantity INTEGER NOT NULL,
    price DECIMAL (4, 2) NOT NULL,
    parentOrder INTEGER NOT NULL,
    product INTEGER NOT NULL,
    CONSTRAINT pk_items PRIMARY KEY (parentOrder, product),
    CONSTRAINT fk_items_order FOREIGN KEY (parentOrder) REFERENCES orders(orderID),
    CONSTRAINT fk_items_product FOREIGN KEY (product) REFERENCES products(productID)
);